controller_node:
  ros__parameters:
    path_topic: /planner_ns/path
    lookahead: 4.0
    base_thrust: 15.0
    heading_kp: 50.0
    heading_kd: 10.0
    max_thrust: 30.0
    max_delta: 15.0
    spline_samples: 400
    samples_per_meter: 4.0

sim_node:
  ros__parameters:
    m: 70.0
    Iz: 10.0
    Xu: 5.0
    Xuu: 1.0
    Yv: 40.0
    Yr: 5.0
    Nv: 5.0
    Nr: 40.0
    l: 0.5
    dt: 0.02
