controller_node:
  ros__parameters:
    path_topic: /planner_ns/path
    lookahead: 4.0
    base_thrust: 15.0
    heading_kp: 2.0
    heading_kd: 0.5
    max_thrust: 30.0
    max_delta: 1.0471975512
    cte_gain: 0.5
    samples_per_meter: 4.0
    max_proj_jump: 0.2

sim_node:
  ros__parameters:
    m: 70.0
    Iz: 10.0
    Xu: 5.0
    Xuu: 1.0
    Yv: 40.0
    Yr: 5.0
    Nv: 5.0
    Nr: 40.0
    l: 0.5
    dt: 0.02
    max_thrust: 40.0
    max_delta: 1.0471975512
    max_delta_rate: 0.0

viz_node:
  ros__parameters:
    convert_legacy_ned_to_enu: false
    use_urdf: true
    urdf_path: /root/code/src/na_launch/urdf/boat.urdf
    debug_marker_z_offset: 4.0
