controller_node:
  ros__parameters:
    path_topic: /planner_ns/path
    lookahead: 1.5
    base_thrust: 20.0
    heading_kp: 8.0
    heading_kd: 1.5
    max_thrust: 40.0
    max_delta: 1.57079632679
    samples_per_meter: 4.0
    max_proj_jump: 0.2

sim_node:
  ros__parameters:
    sim_model: 6dof
    integrator: expmap
    m: 70.0
    Ix: 10.0
    Iy: 10.0
    Iz: 10.0
    Xu: 5.0
    Xuu: 1.0
    Yv: 40.0
    Yr: 5.0
    Nv: 5.0
    Nr: 40.0
    Zw: 0.0
    Kp: 0.0
    Mq: 0.0
    Yvv: 0.0
    Zww: 0.0
    Kpp: 0.0
    Mqq: 0.0
    Nrr: 0.0
    added_mass_x: 0.0
    added_mass_y: 0.0
    added_mass_z: 0.0
    added_mass_k: 0.0
    added_mass_m: 0.0
    added_mass_n: 0.0
    r_g_x: 0.0
    r_g_y: 0.0
    r_g_z: 0.0
    r_b_x: 0.0
    r_b_y: 0.0
    r_b_z: 0.0
    weight: -1.0
    buoyancy: -1.0
    l: 0.5
    dt: 0.02
    max_thrust: 40.0
    max_delta: 1.57079632679
    max_delta_rate: 1.0
